version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bakery
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=1
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBIT_QUEUE=bakery
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:1.27-alpine
    container_name: bakery-nginx
    ports:
      - "8070:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  rabbitmq:
      image: rabbitmq:3.13-management
      container_name: bakery-rabbit
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: bakery
        RABBITMQ_DEFAULT_PASS: bakery
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq

volumes:
  dbdata:
  rabbitmq_data:
